package common

const (
	DEFAULT_TAG string = "default"

	CAPTCHA_NAME_SLIDER     = "SLIDER"
	CAPTCHA_NAME_ROTATE     = "ROTATE"
	CAPTCHA_NAME_WORD_CLICK = "WORD_CLICK"

	TEMPLATE_ACTIVE_IMAGE_NAME = "active.png"
	TEMPLATE_FIXED_IMAGE_NAME  = "fixed.png"

	TRACK_TYPE_UP    = "UP"
	TRACK_TYPE_DOWN  = "DOWN"
	TRACK_TYPE_MOVE  = "MOVE"
	TRACK_TYPE_CLICK = "CLICK"
)
